#ignore all these data.table column names
utils::globalVariables(
  c(" NO_PRJ_MES", ".", ".N", ".SD", ":=", "AB_forestry", "AGE",
    "AGE_SANSOP", "AgeHeaderKey", "ageMethod", "AgeSampleKey", "AgeSampleStatusCode",
    "AgeSampleTypeCode", "AgeTreeKey", "ALTITUDE", "area_pm", "baseAgeYear",
    "baseSA", "baseStandAge", "baseTreeAge", "baseYear", "BC_forestry",
    "cause", "cause1", "cause2", "cause3", "CL_QUAL", "CommonName",
    "company_plot_number", "CONDCOD1", "CONDCOD2", "CONDCOD3", "condition_code1",
    "CONDITION_CODE1", "condition_code2", "CONDITION_CODE2", "condition_code3",
    "CONDITION_CODE3", "CoordTypeCode", "crown_class", "CROWN_CLASS",
    "CrownClassCode", "CrownClsr", "CRZ_EAST", "CRZ_ZONE", "CRZNORTH",
    "dam_1", "dam_2", "dam_3", "dam_4", "dam_5", "Damage Agent Code",
    "damage_agent", "DATE_SOND", "Datum", "dbh", "DBH", "dbh_age", "dbhlimit_tag",
    "DERN_SOND", "DHP", "Easting", "elev", "elevation", "Elevation",
    "ESSENCE", "EstabAge", "EstabDate", "EstabYear", "ETAGE_ARB",
    "ETAT", "FieldAge", "FieldAge_Base", "FieldAge_DBH", "FieldAge_diff",
    "FieldSeasonYear", "firstAgeMsrYear", "firstMsrYear", "fullGenusSpec",
    "Genus", "group", "GrowthPlotNum", "HAUT_ARBRE", "height", "Height",
    "HEIGHT", "HtTot", "ID_ARB_MES", "ID_ARBRE", "ID_FOR", "ID_PE",
    "ID_PE_MES", "IN_GPS", "isArtificial", "IsBad", "lat", "Latin_full",
    "LatinName", "latitude", "LATITUDE", "Length", "lgtree_genus",
    "lgtree_species", "lgtree_status", "LocPlotKey", "long_", "longitude",
    "LONGITUDE", "maxN", "meas_date", "meas_num", "meas_plot_size",
    "meas_yr", "measNum", "MeasNum", "MeasureID", "measurement_number",
    "measurement_year", "MeasureYear", "MeasYr", "MeausreYear", "minMeasure",
    "MORTALITY", "mostRecentMsr", "MsrDate", "N", "nCodominant", "nDominant",
    "nfi_plot", "NO_ARBRE", "NO_MES", "NO_PE", "NO_PRJ", "NO_VIREE", "NofTrees",
    "Northing", "numAreas", "OFFICE_ERROR", "OfficeAge", "OfficeAge_Base",
    "OfficeAge_DBH", "OfficeAge_diff", "orig_plot_area", "ORIGINE",
    "OrigPlotID1", "OrigPlotID2", "P_AGECLS", "PackageKey", "PERTURB",
    "Plot", "PLOT", "PLOT_ID", "PLOT_SIZE", "plotArea", "PlotKey",
    "PlotName", "PLOTNUM", "PlotSize", "PlotType", "PSIZE", "PSP",
    "QCPSP", "Radius", "RemeasID", "RESEAU", "SA", "SAMP_ID", "SilvID",
    "site_age", "sizes", "SK_forestry", "SOURCE_AGE", "SpecCode",
    "SpecCommon", "SpecGenus", "species", "Species", "SPECIES", "SpeciesCode",
    "SpecSpec", "stand_age", "stand_origin", "standardizedAge", "StartYear",
    "stnd_org", "stump_age", "sub_plot_tree", "tempyear", "tot_stand_age",
    "total_age", "TOTAL_AGE", "totalBad", "treatment", "treatmenttimes",
    "TreatTypeName", "TreatYear", "tree_cls", "tree_location_id",
    "tree_no", "TREE_NO", "tree_num", "tree_number", "tree_origin",
    "tree_plot_area", "TREE_STATUS", "treeAge", "TreeGrowthPlotKey",
    "TreeHeaderKey", "TreeKey", "TreeMsrKey", "TREENO", "treenum",
    "TreeNum", "TreeNumber", "TreeOriginCode", "TreeRenumber", "trees_measurement_comment",
    "TreeStatusCode", "tree_tagging_limit", "TYPE_PE", "unifiedAge", "utm_e",
    "utm_easting", "utm_n", "utm_northing", "utm_zone", "VERSION", "VisitTypeName",
    "Width", "year", "YEAR", "Z13nad83_e", "Z13nad83_n", "zone",

    "Zone"))
